Some simple renaming

diff --git a/.github/workflows/ci-with-secrets.yml b/.github/workflows/ci-with-secrets.yml
--- a/.github/workflows/ci-with-secrets.yml
+++ b/.github/workflows/ci-with-secrets.yml
@@ -1,4 +1,4 @@
-name: End To End Tests
+name: CI With Secrets
 on:
   push: { branches: [main] }
   pull_request_target: {}
@@ -97,34 +97,37 @@ jobs:
           tags: ${{ env.repository }}:${{ env.production-tag }}
 
   check-javascript-asset-size:
-    name: Check Javascript Asset Size
+    name: Javascript Asset Size Not Too Big
     runs-on: ubuntu-20.04
     container: sctrainer/main:production-${{ github.sha }}
-    needs: build-docker-containers
+    needs: [build-docker-containers, is-trusted]
     steps:
       - name: Install Bash (as production image doesn't include it)
         run: apk add bash
 
       - name: Check Javascript Asset Filesize Less Than 200Kb
         shell: bash
-        run: |
+        run: >
           num_bytes=$(gzip /app/public/main.js -c | wc -c)
+
           RED='\033[0;31m'
-          (( num_bytes < (200 * 1000) )) || \
-            (\
-              echo -e "${RED}ERROR: Javascript Asset Size Has Grown Unexpectedly. Gzipped Size Is Now $num_bytes bytes" \
-              && exit 1 \
+
+          (( num_bytes < (200 * 1000) )) ||
+            (
+              echo -e "${RED}ERROR: Javascript Asset Size Has Grown Unexpectedly.
+              Gzipped Size Is Now $num_bytes bytes" &&
+              exit 1
             )
 
   cypress-end-to-end-tests:
-    name: "${{ matrix.platform.browserString }} on screen size of ${{ matrix.sizeRelevant.deviceName }} Linux Cypress E2E Tests"
+    name: "Cypress E2E tests for ${{ matrix.platform.browserString }} on screen size of ${{ matrix.sizeRelevant.deviceName }}"
     runs-on: ubuntu-20.04
     container:
       image: sctrainer/main:ci-chrome-v1
       # This is needed for Firefox running as described here
       # https://github.com/cypress-io/github-action/issues/104
       options: --user 1001
-    needs: build-docker-containers
+    needs: [build-docker-containers, is-trusted]
     env:
       PORT: 8080
     services:
