Try optimizing the CI workflow a bit

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -6,16 +6,93 @@ on:
 permissions:
   contents: read
 
+env:
+  repository: sctrainer/main
+
 jobs:
-  wait-for-docker-containers:
-    name: Wait For Docker Containers To Be Built And Pushed
+  wait-for-ci-container:
+    name: Wait For CI Container To Be Built And Pushed
     runs-on: ubuntu-20.04
     outputs:
       ci-container: ${{ steps.outputter.outputs.ci-container }}
+    # Dependabot doesn't receive secrets on a push event
+    # so can't run our CI, so we just skip CI for it.
+    # We have settings set up that ensure it can't be merged without
+    # being up to date with main, so it shouldn't be an issue
+    if: ${{ !( github.event_name == 'push' && github.event.sender.login == 'dependabot[bot]' ) }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - name: Get container tags
+        id: tags
+        run: echo "ci-container=ci-container-v7" >> $GITHUB_OUTPUT
+
+      - name: Wait for CI Container image to exist
+        shell: bash
+        run: |
+          SECONDS=0
+          max_wait_time=300
+          wait_interval=5
+
+          while (( SECONDS  < max_wait_time )); do
+            curl --silent -f -lSL https://hub.docker.com/v2/repositories/${{ env.repository }}/tags/${{ steps.tags.outputs.ci-container }} && break;
+            echo "Failed so sleeping"
+            sleep $wait_interval
+            echo "Trying again"
+          done
+
+          (( SECONDS >= max_wait_time )) && echo "failed" && exit 1
+          echo "Success"
+
+      - name: Output the container names
+        id: outputter
+        run: echo "ci-container=${{ env.repository }}:${{ steps.tags.outputs.ci-container }}" >> $GITHUB_OUTPUT
+
+  wait-for-ci-chrome-container:
+    name: Wait For CI Chrome Container To Be Built And Pushed
+    runs-on: ubuntu-20.04
+    outputs:
       ci-chrome: ${{ steps.outputter.outputs.ci-chrome }}
+    # Dependabot doesn't receive secrets on a push event
+    # so can't run our CI, so we just skip CI for it.
+    # We have settings set up that ensure it can't be merged without
+    # being up to date with main, so it shouldn't be an issue
+    if: ${{ !( github.event_name == 'push' && github.event.sender.login == 'dependabot[bot]' ) }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - name: Get container tags
+        id: tags
+        run: echo "ci-chrome=ci-chrome-v4" >> $GITHUB_OUTPUT
+
+      - name: Wait for CI Chrome image to exist
+        shell: bash
+        run: |
+          SECONDS=0
+          max_wait_time=300
+          wait_interval=5
+
+          while (( SECONDS  < max_wait_time )); do
+            curl --silent -f -lSL https://hub.docker.com/v2/repositories/${{ env.repository }}/tags/${{ steps.tags.outputs.ci-chrome }} && break;
+            echo "Failed so sleeping"
+            sleep $wait_interval
+            echo "Trying again"
+          done
+
+          (( SECONDS >= max_wait_time )) && echo "failed" && exit 1
+          echo "Success"
+
+      - name: Output the container names
+        id: outputter
+        run: echo "ci-chrome=${{ env.repository }}:${{ steps.tags.outputs.ci-chrome }}" >> $GITHUB_OUTPUT
+
+  wait-for-production-container:
+    name: Wait For Production Container To Be Built And Pushed
+    runs-on: ubuntu-20.04
+    outputs:
       production: ${{ steps.outputter.outputs.production }}
-    env:
-      repository: sctrainer/main
     # Dependabot doesn't receive secrets on a push event
     # so can't run our CI, so we just skip CI for it.
     # We have settings set up that ensure it can't be merged without
@@ -47,43 +124,7 @@ jobs:
             ) \
           )
 
-          echo "ci-container=ci-container-v7" >> $GITHUB_OUTPUT
-          echo "ci-chrome=ci-chrome-v4" >> $GITHUB_OUTPUT
           echo "production=production-$SHA" >> $GITHUB_OUTPUT
-
-      - name: Wait for CI Container image to exist
-        shell: bash
-        run: |
-          SECONDS=0
-          max_wait_time=300
-          wait_interval=5
-
-          while (( SECONDS  < max_wait_time )); do
-            curl --silent -f -lSL https://hub.docker.com/v2/repositories/${{ env.repository }}/tags/${{ steps.tags.outputs.ci-container }} && break;
-            echo "Failed so sleeping"
-            sleep $wait_interval
-            echo "Trying again"
-          done
-
-          (( SECONDS >= max_wait_time )) && echo "failed" && exit 1
-          echo "Success"
-
-      - name: Wait for CI Chrome image to exist
-        shell: bash
-        run: |
-          SECONDS=0
-          max_wait_time=300
-          wait_interval=5
-
-          while (( SECONDS  < max_wait_time )); do
-            curl --silent -f -lSL https://hub.docker.com/v2/repositories/${{ env.repository }}/tags/${{ steps.tags.outputs.ci-chrome }} && break;
-            echo "Failed so sleeping"
-            sleep $wait_interval
-            echo "Trying again"
-          done
-
-          (( SECONDS >= max_wait_time )) && echo "failed" && exit 1
-          echo "Success"
 
       - name: Wait for Production image to exist
         shell: bash
@@ -104,15 +145,12 @@ jobs:
 
       - name: Output the container names
         id: outputter
-        run: |
-          echo "ci-container=${{ env.repository }}:${{ steps.tags.outputs.ci-container }}" >> $GITHUB_OUTPUT
-          echo "ci-chrome=${{ env.repository }}:${{ steps.tags.outputs.ci-chrome }}" >> $GITHUB_OUTPUT
-          echo "production=${{ env.repository }}:${{ steps.tags.outputs.production }}" >> $GITHUB_OUTPUT
+        run: echo "production=${{ env.repository }}:${{ steps.tags.outputs.production }}" >> $GITHUB_OUTPUT
 
   lint-and-unit-tests:
     name: Linting And Unit Tests
     runs-on: ubuntu-20.04
-    needs: wait-for-docker-containers
+    needs: wait-for-ci-container
     container:
       image: ${{ needs.wait-for-docker-containers.outputs.ci-container }}
       # This is to appease the new strict directory ownership checks announced here:
@@ -187,7 +225,7 @@ jobs:
   check-javascript-asset-size:
     name: Javascript Asset Size Not Too Big
     runs-on: ubuntu-20.04
-    needs: wait-for-docker-containers
+    needs: wait-for-production-container
     container: ${{ needs.wait-for-docker-containers.outputs.production }}
     # Dependabot doesn't receive secrets on a push event
     # so can't run our CI, so we just skip CI for it.
@@ -216,7 +254,7 @@ jobs:
       Cypress E2E tests for ${{ matrix.platform.browserString }}
       on screen size of ${{ matrix.sizeRelevant.deviceName }}
     runs-on: ubuntu-20.04
-    needs: wait-for-docker-containers
+    needs: wait-for-ci-chrome-container
     container:
       image: ${{ needs.wait-for-docker-containers.outputs.ci-chrome }}
       # This is needed for Firefox running as described here
